# Generated by Django 3.2.3 on 2021-10-18 03:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('test111', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyClassify',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False, verbose_name='UUID')),
                ('isActive', models.BooleanField(default=True, verbose_name='是否有效')),
                ('deleteTime', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modifyTime', models.DateTimeField(auto_now=True, verbose_name='最新修改时间')),
                ('label', models.CharField(max_length=16, verbose_name='类型名称')),
                ('key', models.CharField(db_index=True, max_length=16, verbose_name='类型键值')),
                ('allowance', models.FloatField(default=0, max_length=16, verbose_name='基础津贴')),
                ('subsidizedMeals', models.FloatField(default=0, max_length=16, verbose_name='餐饮补贴')),
                ('color', models.CharField(blank=True, default='#000000', max_length=32, null=True, verbose_name='渲染颜色')),
            ],
            options={
                'unique_together': {('key', 'deleteTime')},
            },
        ),
        migrations.CreateModel(
            name='HolidaysAndFestivals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False, verbose_name='UUID')),
                ('isActive', models.BooleanField(default=True, verbose_name='是否有效')),
                ('deleteTime', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modifyTime', models.DateTimeField(auto_now=True, verbose_name='最新修改时间')),
                ('date', models.DateField(verbose_name='日期')),
                ('name', models.CharField(max_length=64, verbose_name='假日名称')),
            ],
            options={
                'unique_together': {('date', 'deleteTime')},
            },
        ),
        migrations.CreateModel(
            name='HolidaysAndFestivalsPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False, verbose_name='UUID')),
                ('isActive', models.BooleanField(default=True, verbose_name='是否有效')),
                ('deleteTime', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modifyTime', models.DateTimeField(auto_now=True, verbose_name='最新修改时间')),
                ('allowanceMultiple', models.FloatField(default=1, max_length=2, verbose_name='基本津贴倍数')),
                ('totalAllowance', models.FloatField(default=0, max_length=4, verbose_name='总津贴')),
                ('subsidizedMealsMultiple', models.FloatField(default=1, max_length=2, verbose_name='餐饮补贴倍数')),
                ('totalSubsidizedMeals', models.FloatField(default=0, max_length=4, verbose_name='总餐补')),
                ('classify', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hf_plan_classify', to='test111.dutyclassify', verbose_name='值班类型')),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hf_plan_festival', to='test111.holidaysandfestivals', verbose_name='节假日')),
            ],
            options={
                'unique_together': {('festival', 'classify', 'deleteTime')},
            },
        ),
    ]
