# Generated by Django 3.2.3 on 2021-10-18 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test111', '0002_dutyclassify_holidaysandfestivals_holidaysandfestivalsplan'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='holidaysandfestivalsplan',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='holidaysandfestivalsplan',
            name='classify',
        ),
        migrations.DeleteModel(
            name='DutyClassify',
        ),
    ]
