# Generated by Django 3.2.3 on 2021-10-18 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0030_auto_20211012_1032'),
        ('test111', '0003_auto_20211018_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaysandfestivalsplan',
            name='classify',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_hf_plan_classify', to='personnel.dutyclassify', verbose_name='值班类型'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='holidaysandfestivalsplan',
            name='festival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_hf_plan_festival', to='test111.holidaysandfestivals', verbose_name='节假日'),
        ),
        migrations.AlterUniqueTogether(
            name='holidaysandfestivalsplan',
            unique_together={('festival', 'classify', 'deleteTime')},
        ),
    ]
