# Generated by Django 3.2.3 on 2021-10-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test111', '0004_auto_20211018_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaysandfestivals',
            name='deleteTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AlterField(
            model_name='holidaysandfestivalsplan',
            name='deleteTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
    ]
