# Generated by Django 3.2.3 on 2021-08-10 03:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DutyClassify',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False, verbose_name='UUID')),
                ('isActive', models.BooleanField(default=True, verbose_name='是否有效')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modifyTime', models.DateTimeField(auto_now=True, verbose_name='最新修改时间')),
                ('label', models.CharField(max_length=16, verbose_name='类型名称')),
                ('key', models.CharField(max_length=16, verbose_name='类型键值')),
                ('allowance', models.FloatField(max_length=16, verbose_name='基础津贴')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DutyPersonnel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False, verbose_name='UUID')),
                ('isActive', models.BooleanField(default=True, verbose_name='是否有效')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modifyTime', models.DateTimeField(auto_now=True, verbose_name='最新修改时间')),
                ('name', models.CharField(max_length=64, verbose_name='人员姓名')),
                ('classify', models.ManyToManyField(to='personnel.DutyClassify')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
