# Generated by Django 3.2.3 on 2021-08-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutypersonnel',
            name='sequence',
            field=models.IntegerField(default=0, help_text='默认正序排列', max_length=8, verbose_name='值班顺序'),
        ),
    ]
