# Generated by Django 3.2.3 on 2021-08-13 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_dutypersonnel_sequence'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dutyclassify',
            unique_together={('key', 'isActive')},
        ),
    ]
