# Generated by Django 3.2.3 on 2021-08-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_alter_dutyclassify_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutyclassify',
            name='color',
            field=models.CharField(blank=True, default='#000000', max_length=16, verbose_name='渲染颜色'),
        ),
        migrations.AlterField(
            model_name='dutypersonnel',
            name='sequence',
            field=models.IntegerField(default=0, help_text='默认正序排列', verbose_name='值班顺序'),
        ),
    ]
