# Generated by Django 3.2.3 on 2021-08-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_auto_20210826_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutyclassify',
            name='color',
            field=models.CharField(blank=True, default='#000000', max_length=16, null=True, verbose_name='渲染颜色'),
        ),
    ]
