# Generated by Django 3.2.3 on 2021-08-30 08:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0006_alter_dutyclassify_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False, verbose_name='UUID')),
                ('isActive', models.BooleanField(default=True, verbose_name='是否有效')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modifyTime', models.DateTimeField(auto_now=True, verbose_name='最新修改时间')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='日期')),
                ('b', models.CharField(blank=True, max_length=64, verbose_name='白班')),
                ('w', models.CharField(max_length=64, verbose_name='晚班')),
                ('yuy', models.CharField(max_length=64, verbose_name='运营班')),
                ('yiy', models.CharField(max_length=64, verbose_name='应用班')),
                ('aq', models.CharField(max_length=64, verbose_name='安全班')),
                ('change', models.IntegerField(default=0, help_text='仅记录当天换班次数，0表示没有换班。', verbose_name='换班次数')),
                ('holiday', models.BooleanField(default=False, verbose_name='是否假日')),
                ('allowanceMultiple', models.FloatField(default=1, help_text='一般用于计算节假日基础津贴，休假日默认1倍。', verbose_name='津贴倍数')),
                ('subsidizedMealsMultiple', models.FloatField(default=1, help_text='一般用于计算节假日基础津贴，休假日默认1倍。', verbose_name='餐补倍数')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dutyclassify',
            name='subsidizedMeals',
            field=models.FloatField(default=0, max_length=16, verbose_name='餐饮补贴'),
        ),
        migrations.AlterField(
            model_name='dutyclassify',
            name='allowance',
            field=models.FloatField(default=0, max_length=16, verbose_name='基础津贴'),
        ),
    ]
