# Generated by Django 3.2.3 on 2021-09-07 01:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0007_auto_20210830_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidaysAndFestivals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False, verbose_name='UUID')),
                ('isActive', models.BooleanField(default=True, verbose_name='是否有效')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modifyTime', models.DateTimeField(auto_now=True, verbose_name='最新修改时间')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='日期')),
                ('name', models.CharField(max_length=64, verbose_name='假日名称')),
                ('plan', models.TextField(verbose_name='倍数计划')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='dutycalendar',
            name='allowanceMultiple',
        ),
        migrations.RemoveField(
            model_name='dutycalendar',
            name='aq',
        ),
        migrations.RemoveField(
            model_name='dutycalendar',
            name='b',
        ),
        migrations.RemoveField(
            model_name='dutycalendar',
            name='change',
        ),
        migrations.RemoveField(
            model_name='dutycalendar',
            name='subsidizedMealsMultiple',
        ),
        migrations.RemoveField(
            model_name='dutycalendar',
            name='w',
        ),
        migrations.RemoveField(
            model_name='dutycalendar',
            name='yiy',
        ),
        migrations.RemoveField(
            model_name='dutycalendar',
            name='yuy',
        ),
        migrations.AddField(
            model_name='dutycalendar',
            name='plan',
            field=models.TextField(default='', verbose_name='排班计划'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dutycalendar',
            name='festival',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='personnel.holidaysandfestivals', verbose_name='节日'),
            preserve_default=False,
        ),
    ]
