# Generated by Django 3.2.3 on 2021-09-07 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0008_auto_20210907_0903'),
    ]

    operations = [
    ]
