# Generated by Django 3.2.3 on 2021-09-07 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0009_alter_holidaysandfestivals_plan'),
    ]

    operations = [
    ]
