# Generated by Django 3.2.3 on 2021-09-07 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0011_alter_holidaysandfestivals_plan'),
    ]

    operations = [
    ]
