# Generated by Django 3.2.3 on 2021-09-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0012_alter_holidaysandfestivals_plan'),
    ]

    operations = [
    ]
