# Generated by Django 3.2.3 on 2021-09-08 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0014_alter_holidaysandfestivals_plan'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='holidaysandfestivals',
            unique_together={('date', 'isActive')},
        ),
    ]
