# Generated by Django 3.2.3 on 2021-09-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0015_alter_holidaysandfestivals_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutyclassify',
            name='key',
            field=models.CharField(db_index=True, max_length=16, verbose_name='类型键值'),
        ),
        migrations.AlterField(
            model_name='holidaysandfestivals',
            name='date',
            field=models.DateField(db_index=True, verbose_name='日期'),
        ),
    ]
