# Generated by Django 3.2.3 on 2021-09-08 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0017_alter_dutycalendar_festival'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dutycalendar',
            unique_together={('date', 'isActive')},
        ),
    ]
