# Generated by Django 3.2.3 on 2021-09-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0019_alter_dutycalendar_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutypersonnel',
            name='tel',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='联系电话'),
        ),
    ]
