# Generated by Django 3.2.3 on 2021-09-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0020_dutypersonnel_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutypersonnel',
            name='tel',
            field=models.CharField(default='', max_length=16, verbose_name='联系电话'),
        ),
    ]
