# Generated by Django 3.2.3 on 2021-09-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0022_auto_20210916_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaysandfestivals',
            name='plan',
            field=models.TextField(default='', verbose_name='倍数计划'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='holidaysandfestivals',
            unique_together={('date', 'isActive')},
        ),
        migrations.RemoveField(
            model_name='holidaysandfestivals',
            name='allowanceMultiple',
        ),
        migrations.RemoveField(
            model_name='holidaysandfestivals',
            name='classify',
        ),
        migrations.RemoveField(
            model_name='holidaysandfestivals',
            name='subsidizedMealsMultiple',
        ),
        migrations.RemoveField(
            model_name='holidaysandfestivals',
            name='totalAllowance',
        ),
        migrations.RemoveField(
            model_name='holidaysandfestivals',
            name='totalSubsidizedMeals',
        ),
    ]
