# Generated by Django 3.2.3 on 2021-10-11 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0024_auto_20211011_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidaysandfestivals',
            name='plan',
        ),
    ]
