# Generated by Django 3.2.3 on 2021-10-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0025_remove_holidaysandfestivals_plan'),
    ]

    operations = [
    ]
