# Generated by Django 3.2.3 on 2021-10-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0026_auto_20211011_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutycalendar',
            name='deleteTime',
            field=models.DateTimeField(null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='dutyclassify',
            name='deleteTime',
            field=models.DateTimeField(null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='dutypersonnel',
            name='deleteTime',
            field=models.DateTimeField(null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='holidaysandfestivals',
            name='deleteTime',
            field=models.DateTimeField(null=True, verbose_name='删除时间'),
        ),
    ]
