# Generated by Django 3.2.3 on 2021-10-11 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0027_auto_20211011_1542'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='holidaysandfestivals',
            unique_together={('date', 'classify', 'deleteTime')},
        ),
        migrations.AlterUniqueTogether(
            name='dutycalendar',
            unique_together={('date', 'deleteTime')},
        ),
        migrations.AlterUniqueTogether(
            name='dutyclassify',
            unique_together={('key', 'deleteTime')},
        ),
    ]
