# Generated by Django 3.2.3 on 2021-10-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0028_auto_20211011_1542'),
    ]

    operations = [
    ]
