# Generated by Django 3.2.3 on 2021-10-12 02:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0029_auto_20211011_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutycalendar',
            name='festival',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='duty_calendar_festival', to='personnel.holidaysandfestivals', verbose_name='节假日'),
        ),
        migrations.AlterUniqueTogether(
            name='holidaysandfestivals',
            unique_together={('date', 'deleteTime')},
        ),
        migrations.RemoveField(
            model_name='holidaysandfestivals',
            name='allowanceMultiple',
        ),
        migrations.RemoveField(
            model_name='holidaysandfestivals',
            name='classify',
        ),
        migrations.RemoveField(
            model_name='holidaysandfestivals',
            name='subsidizedMealsMultiple',
        ),
        migrations.RemoveField(
            model_name='holidaysandfestivals',
            name='totalAllowance',
        ),
        migrations.RemoveField(
            model_name='holidaysandfestivals',
            name='totalSubsidizedMeals',
        ),
        migrations.CreateModel(
            name='HolidaysAndFestivalsPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False, verbose_name='UUID')),
                ('isActive', models.BooleanField(default=True, verbose_name='是否有效')),
                ('deleteTime', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modifyTime', models.DateTimeField(auto_now=True, verbose_name='最新修改时间')),
                ('allowanceMultiple', models.FloatField(default=1, max_length=2, verbose_name='基本津贴倍数')),
                ('totalAllowance', models.FloatField(default=0, max_length=4, verbose_name='总津贴')),
                ('subsidizedMealsMultiple', models.FloatField(default=1, max_length=2, verbose_name='餐饮补贴倍数')),
                ('totalSubsidizedMeals', models.FloatField(default=0, max_length=4, verbose_name='总餐补')),
                ('classify', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hf_plan_classify', to='personnel.dutyclassify', verbose_name='值班类型')),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hf_plan_festival', to='personnel.holidaysandfestivals', verbose_name='节假日')),
            ],
            options={
                'unique_together': {('festival', 'classify', 'deleteTime')},
            },
        ),
    ]
