# Generated by Django 3.2.3 on 2021-11-03 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0032_auto_20211018_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutycalendar',
            name='deleteTime',
            field=models.CharField(default='', max_length=19, verbose_name='删除时间'),
        ),
        migrations.AlterField(
            model_name='dutyclassify',
            name='deleteTime',
            field=models.CharField(default='', max_length=19, verbose_name='删除时间'),
        ),
        migrations.AlterField(
            model_name='dutypersonnel',
            name='deleteTime',
            field=models.CharField(default='', max_length=19, verbose_name='删除时间'),
        ),
        migrations.AlterField(
            model_name='holidaysandfestivals',
            name='deleteTime',
            field=models.CharField(default='', max_length=19, verbose_name='删除时间'),
        ),
        migrations.AlterField(
            model_name='holidaysandfestivalsplan',
            name='classify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='festival_classify', to='personnel.dutyclassify', verbose_name='值班类型'),
        ),
        migrations.AlterField(
            model_name='holidaysandfestivalsplan',
            name='deleteTime',
            field=models.CharField(default='', max_length=19, verbose_name='删除时间'),
        ),
        migrations.AlterField(
            model_name='holidaysandfestivalsplan',
            name='festival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='festival_plan', to='personnel.holidaysandfestivals', verbose_name='节假日'),
        ),
    ]
