# Generated by Django 3.2.3 on 2021-11-03 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0033_auto_20211103_1457'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='holidaysandfestivals',
            unique_together={('date', 'name')},
        ),
    ]
