# Generated by Django 3.2.3 on 2021-11-03 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0034_alter_holidaysandfestivals_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='holidaysandfestivals',
            unique_together={('date', 'deleteTime')},
        ),
    ]
