# Generated by Django 3.2.3 on 2021-11-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0036_auto_20211103_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutycalendar',
            name='deleteTime',
            field=models.CharField(default='', max_length=19, verbose_name='删除时间'),
        ),
        migrations.AlterField(
            model_name='dutyclassify',
            name='deleteTime',
            field=models.CharField(default='', max_length=19, verbose_name='删除时间'),
        ),
        migrations.AlterField(
            model_name='dutypersonnel',
            name='deleteTime',
            field=models.CharField(default='', max_length=19, verbose_name='删除时间'),
        ),
        migrations.AlterField(
            model_name='holidaysandfestivals',
            name='deleteTime',
            field=models.CharField(default='', max_length=19, verbose_name='删除时间'),
        ),
        migrations.AlterField(
            model_name='holidaysandfestivalsplan',
            name='deleteTime',
            field=models.CharField(default='', max_length=19, verbose_name='删除时间'),
        ),
    ]
