# Generated by Django 3.2.3 on 2021-11-04 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0037_auto_20211103_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaysandfestivalsplan',
            name='festival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='festival_plan', to='personnel.holidaysandfestivals', verbose_name='节假日'),
        ),
    ]
