# Generated by Django 3.2.3 on 2021-11-04 03:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0038_alter_holidaysandfestivalsplan_festival'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dutycalendar',
            name='plan',
        ),
        migrations.AlterField(
            model_name='dutycalendar',
            name='festival',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='calendar_festival', to='personnel.holidaysandfestivals', verbose_name='节假日'),
        ),
        migrations.CreateModel(
            name='DutyCalendarPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False, verbose_name='UUID')),
                ('isActive', models.BooleanField(default=True, verbose_name='是否有效')),
                ('deleteTime', models.CharField(default='', max_length=19, verbose_name='删除时间')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modifyTime', models.DateTimeField(auto_now=True, verbose_name='最新修改时间')),
                ('totalAllowance', models.FloatField(default=0, max_length=4, verbose_name='总津贴')),
                ('totalSubsidizedMeals', models.FloatField(default=0, max_length=4, verbose_name='总餐补')),
                ('classify', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='calendar_classify', to='personnel.dutyclassify', verbose_name='值班类型')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_plan', to='personnel.dutycalendar', verbose_name='值班日期')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='calendar_personnel', to='personnel.dutypersonnel', verbose_name='值班人员')),
            ],
            options={
                'unique_together': {('date', 'classify', 'deleteTime')},
            },
        ),
    ]
