# Generated by Django 3.2.3 on 2021-11-05 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0039_auto_20211104_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutyclassify',
            name='doubleShift',
            field=models.BooleanField(default=False, verbose_name='假日双班'),
        ),
    ]
