# Generated by Django 3.2.3 on 2021-11-05 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0041_auto_20211105_1458'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dutyclassify',
            unique_together={('label', 'deleteTime')},
        ),
        migrations.RemoveField(
            model_name='dutyclassify',
            name='key',
        ),
    ]
