# Generated by Django 3.2.3 on 2021-11-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0042_auto_20211105_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutyclassify',
            name='sequence',
            field=models.IntegerField(default=0, help_text='默认正序排列', verbose_name='显示顺序'),
        ),
    ]
